"""add phone number

Revision ID: 447b65282dad
Revises: 68e0deefa312
Create Date: 2021-12-18 12:51:43.627096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447b65282dad'
down_revision = '68e0deefa312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
